group:
  repos: |
    SlavRim/EvaporationPond
    SlavRim/Rebels
    SlavRim/TribalWater
    SlavRim/Glitterpaths
    SlavRim/BounceGun
    SlavRim/DeathTricks
    SlavRim/DominantGene
    SlavRim/ToxVent
    SlavRim/RimworldBetterLoading
    SlavRim/Locks2
    SlavRim/NeuralInterceptMatrix
    SlavRim/HumanStoryteller
  files: 
    - source: Shared.mod.props.csproj
      dest: Shared.mod.props.csproj
    - source: Properties/launchSettings.json
      dest: Properties/launchSettings.json
    - source: .gitignore
      dest: .gitignore
    - source: .editorconfig
      dest: .editorconfig
    - source: .github/workflows/automerge.yml
      dest: .github/workflows/automerge.yml
    - source: .github/workflows/build.yml
      dest: .github/workflows/build.yml