group:
  repos: |
    SlavRim/Lives-Matter
    SlavRim/DominantGene
  files: 
    - source: Shared.mod.props.csproj
      dest: Shared.mod.props.csproj
    - source: Properties/launchSettings.json
      dest: Properties/launchSettings.json
    - source: .gitignore
      dest: .gitignore